### ISSUE TITLE
datetime convert

### ISSUE THREAD

**Issue by mayank072015** [GeoscienceAustralia/tcrm#117]
how datetime convert into standard datetime in output 
track data floder

**Comment by wcarthur** [comment]
The [cftime library](https://unidata.github.io/cftime/) can be used to convert from the datetime values to python datetime objects. See the [num2date function](https://unidata.github.io/cftime/api.html#cftime.num2date). Note the units and calendar of the data in the track files are required - these are stored as attributes of the time variable in the netcdf file.
