### ISSUE TITLE
Curly Tracks over Australia Using Default Model and Default Dataset

### ISSUE THREAD

**Issue by shoebansari3555rms** [GeoscienceAustralia/tcrm#135]
We have used IBTrACS dataset for Australia region and have run one simulation for Australia (1981-2016), and found curly track distribution over Australia region. Is it correct or not , can you please comment on it and can you suggest how can we rectify it
![Image20220629152106](https://user-images.githubusercontent.com/108399662/176409116-1842fb69-bd68-4493-84d8-ed17ba46a540.jpg)
.

Also, we have followed the same paper and generated the figure of bearing ,speed and pressure rate auto correlation 1 but they are not matching
![Image20220629153038](https://user-images.githubusercontent.com/108399662/176409764-5715260f-ef90-4d60-b73c-f0f7122c9b0f.jpg)
![Image20220629153021](https://user-images.githubusercontent.com/108399662/176409784-24acaf8a-cd56-46ac-8591-c86af9afdfc7.jpg)
![Image20220629153028](https://user-images.githubusercontent.com/108399662/176409797-8630ed2f-888a-4d81-b04b-8d37bec9b03e.jpg)
.

Can I request you all to comment on it as soon as possible. 
Thank you.

**Comment by wcarthur** [comment]
Hi @shoebansari3555rms can you please provide a copy of the configuration file used for your simulation? If you have run the windfield component of the model, can you also provide a listing of the attributes from one of the netcdf files (`gust.001-00001.nc`) - this has a copy of all the configuration options, including ones that may not be included in your configuration file

**Comment by wcarthur** [comment]
This issue has been resolved (see #140)
