### ISSUE TITLE
Gates.csv file is not shared. kindly share it please

### ISSUE THREAD

**Issue by khaninspace** [GeoscienceAustralia/tcrm#138]

**Comment by wcarthur** [comment]
@khaninspace - do you require the coastal gates for Australia, or are you investigating another basin? The gates file that I have only covers Australian coastline.

**Comment by wcarthur** [comment]
This is the data I now use for analysing coastal landfalls in Australia. It's a basic shapefile, with line features for each gate. Each gate is approximately 50 km off the (smoothed) coast and is 200 km wide. Gates start in the southwest corner of Australia and are directed in a clockwise direction around the northern coastline.

[gates.zip](https://github.com/GeoscienceAustralia/tcrm/files/11073142/gates.zip)
