### ISSUE TITLE
Deprecated numpy interface

### ISSUE THREAD

**Issue by CEKrause** [GeoscienceAustralia/tcrm#33]
In file included from /apps/python/2.7.6/lib/python2.7/site-packages/numpy/core/include/numpy/ndarraytypes.h:1760,
                 from /apps/python/2.7.6/lib/python2.7/site-packages/numpy/core/include/numpy/ndarrayobject.h:17,
                 from /apps/python/2.7.6/lib/python2.7/site-packages/numpy/core/include/numpy/arrayobject.h:4,
                 from Utilities/akima.c:64:
/apps/python/2.7.6/lib/python2.7/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: #warning "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION"

**Comment by wcarthur** [comment]
This will necessitate rewriting the code for Utilities.KPDF.c and Utilities.akima.c

**Comment by wcarthur** [comment]
The KPDF module is used in StatInterface.circularKDE and StatInterface.KDEParameters. Largely this could be superseded by using statsmodels.nonparametric.kernel_density module

**Comment by wcarthur** [comment]
No longer relevant as C extensions have been removed
