### ISSUE TITLE
Images are missing in the documentation

### ISSUE THREAD

**Issue by ghoshamitag** [GeoscienceAustralia/tcrm#35]
Hi
I think all the images/figures in the documentation are missing. I checked the doc directory and found that there are some figures and have different name .

**Comment by wcarthur** [comment]
Are the images missing from the [online version of the documents](http://geoscienceaustralia.github.io/tcrm), or from a locally built version?

**Comment by ghoshamitag** [comment]
from both the location

**Comment by wcarthur** [comment]
Completed - the images are still from examples generated with the previous major release, so may not reflect the results when using version 2.0.
