### ISSUE TITLE
Update hazard map plotting routines to use a standardised palette

### ISSUE THREAD

**Issue by wcarthur** [GeoscienceAustralia/tcrm#45]
ISO22324 (attached) contains guidelines for color-coding hazard information. Using the `seaborn.blend_palette()` function, we can create a colour palette that matches the recommended schemes. I propose using the 7-category listing set out in Table B-1 in the attached document. 

This will modify [`PlotInterface.maps.selectColormap`](https://github.com/GeoscienceAustralia/tcrm/blob/v2.0/PlotInterface/maps.py#L68) function, specifically line 100, whcih currenctly defines a yellow-orange-red colour palette.

[ISO_22324_2015(en).PDF](https://github.com/GeoscienceAustralia/tcrm/files/1370105/ISO_22324_2015.en.PDF)

**Comment by CEKrause** [comment]
Need to update accompanying unit test `test_maps.py`

**Comment by wcarthur** [comment]
Considering two options - first is the palette as specified. Personally not a fan of the full swath of green as a background. 
![maxwind](https://user-images.githubusercontent.com/4098490/31919769-65f93294-b8b0-11e7-80e6-02f2454e31a8.png)

In this one, I've inserted a white level at the end of the palette. Allows you to easily see the extents of the wind field

![maxwind](https://user-images.githubusercontent.com/4098490/31919807-a0873096-b8b0-11e7-80a6-ca695764b58d.png)
