### ISSUE TITLE
HollandWindProfile using HPa

### ISSUE THREAD

**Issue by glennstone** [GeoscienceAustralia/tcrm#52]
Due to the WindSpeedModel class convert HPa to Pa when calculating dP, and the WindProfileModel class NOT doing so, the HollandWindProfile when called with pressures in HPa produces a profile discontinuous at rMax

**Comment by glennstone** [comment]
Also seems to be some issues with vorticity for the HollandWindProfile

import windmodels
import matplotlib.pyplot as plt
import numpy as np

wp = windmodels.HollandWindProfile(lat=15, lon=0, eP = 1010., cP = 971., rMax = 40e3, beta = 1.3)

print(repr(wp.vMax))

r = 1000*np.linspace(1.,200.)

plt.plot(r, wp.velocity(r))
#plt.show()

wp = windmodels.HollandWindProfile(lat=15, lon=0, eP = 101000., cP = 97100., rMax = 40e3, beta = 1.3)

plt.plot(r, wp.velocity(r))
plt.show()

plt.plot(r, wp.vorticity(r))
plt.plot(r, wp.vorticity(r)-wp.velocity(r)/r)
plt.show()

**Comment by wcarthur** [comment]
The discrepancy between `HollandWindProfile` and `WindSpeedModel` has been resolved in 3a796f6

The discrepancy between `WindProfileModel.vorticity` is the vorticity is defined as (1/r) d(Vr)/dr.
