### ISSUE TITLE
loadData.py forces `num` to be an integer

### ISSUE THREAD

**Issue by CEKrause** [GeoscienceAustralia/tcrm#53]
The `getInitialPositions` function within `loadData.py` assumes that `num` being read in from the input dataset is an integer (line 332). 
In the IBTrACS database, the TC serial number contains letters, and is therefore classed as a string. 
If you read in IBTrACS data with `num` specified for the serial number, it will fail the series of `try` tests, and raise a `ValueError`.

**Comment by wcarthur** [comment]
Closed with commit cd957ae
