### ISSUE TITLE
TravisCI failing on cftime

### ISSUE THREAD

**Issue by wcarthur** [GeoscienceAustralia/tcrm#60]
Tests on TravisCI are failing with the following error:

> =================================================================
> 
> FAIL: Test ncGetTimes returns datetime objects
> ----------------------------------------------------------------------
> Traceback (most recent call last):
>  File "/home/travis/build/GeoscienceAustralia/tcrm/tests/test_nctools.py", line 420, in test_ncGetTimes
>     self.assertEqual(type(times[0]), datetime)
> AssertionError: <class 'cftime._cftime.real_datetime'> != <type 'datetime.datetime'>

Runs without error on local systems. Appears that TravisCI platform has jumped forward with netCDF4 version that splits out cftime to a separate module. 

Branch: `develop`
Commit: `bbb7f1f`

**Comment by benjimin** [comment]
Fixed in commit 34b68465 and merged in release v2.1.3
