### ISSUE TITLE
execution fails on domain with negative degree longitude

### ISSUE THREAD

**Issue by bastianmanz** [GeoscienceAustralia/tcrm#72]
Hi all,

I have recently come across TCRM - great job!

I have managed to run the model for a number of locations outside of Australia, but whenever I set the `gridLimit` parameter in the config file to be somewhere in the western hemisphere (like `gridLimit={'xMin':-78.0,'xMax':-58.0,'yMin':10.0,'yMax':25.0}`), the model keeps increasing the cell size for cell number 0 until the iterations are stopped: `StopIteration: Insufficient grid points in selected domain to estimate storm statistics - please select a larger domain. Samples = 0 / 100` and the execution is halted. This behaviour appears to be entirely independent of the area and location specified in the `gridLimit` (provided it is western hemisphere)... is this incorrect usage of the config file or a code issue?

I have attached an example config file .txt for a reproducible example. I am running the model version 2.1 on linux with default WMO IBTRACS v3 (`Allstorms.ibtracs_wmo.v03r10.csv`) as input data.

[puerto_rico.txt](https://github.com/GeoscienceAustralia/tcrm/files/3286869/puerto_rico.txt)

Cheers,

Bastian

**Comment by katturner11** [comment]
Hi Bastian,
I've been using the TCRM for a while and whenever I run into this problem it's because the model can't find any genesis events in the historical input in the set domain. To solve this, I broadened my domain (gridLimit) till it met the minimum number of events to get 'good enough' statistics to build from (minimum is 100 genesis points).

**Comment by bastianmanz** [comment]
Thanks Kathryn,

But even when I extend the domain to `gridLimit={'xMin': -100.0,'xMax': -15.0,'yMin': 0.0,'yMax': 30.0}` I have the same issue and it occurs immediately on the first cell. This is effectively the entire North Atlantic basin and the IBTrACS v10 file certainly has >100 genesis points in this domain. So, despite successfully reading the IBTrACS file, this data is unavailable when 'GenerateDistributions.py' is executed and I would like to understand why?

**Comment by wcarthur** [comment]
@bastianmanz try using `gridLimit={'xMin': 260.0,'xMax': 345.0,'yMin': 0.0,'yMax': 30.0}`. One of the things about working in the Australian region and into the Pacific is that we have challenges managing domains that span the dateline (180E). A more natural boundary for TC-related mapping (in my opinion) is 0E, as there are very few events that cross this longitude.
