### ISSUE TITLE
initEnvPressure incorrectly sampled

### ISSUE THREAD

**Issue by KayShelton** [GeoscienceAustralia/tcrm#87]
I am not sure if this may be a bug, but it appears that the initEnvPressure in TrackGenerator is not being sampled from the mslp grid correctly.

In generateTracks, the initEnvPressure is retrieved using SamplePressure.get_pressure (in the same script), based on the genesisDay, genesisLon and genesisLat. So, this should vary for every track generated, based on these variables. Is this a correct interpretation?

For the tracks I have generated, this does not appear to be the case. I get the same initEnvPressure for every track in a given simulation, although it does vary between simulations.

I am happy to give more information as needed. I am not yet able to confirm exactly what mslp point is being sampled (and why) as I had neglected to print the genesis day (d'oh!).

**Comment by KayShelton** [comment]
I have figured this issue out. It is a bug. 

When initEnvPressure is first sampled it is saved to initEnvPressure rather than genesisEnvPressure, as done for all other variables. Hence on the 2nd track, initEnvPressure exists, so does not resample. A find an replace for all initEnvPressure in generateTracks function (except at the function declaration) fixes this.

**Comment by wcarthur** [comment]
Captured in 8ffe180
