### ISSUE TITLE
Missing unit conversion in metutils.convert

### ISSUE THREAD

**Issue by KayShelton** [GeoscienceAustralia/tcrm#94]
It seems there is a missing unit conversion in metutils.convert. No conversions are supplied for converting m into anything else.

In metutils.convert, a conversion for m needs adding, of the form:
```
    m = {"km":0.001, "mi":0.000621371, "deg":0.00000899886, "nm":0.000539957,
          "rad":0.0000001570783}
```
Additionally, should the km to m conversion not be 
```
    km = {"m":1000., 
```
rather than
```
    km = {"m":0.001,
```

**Comment by wcarthur** [comment]
Fixed in f37e86b8
