### ISSUE TITLE
Missing bandwidth giving errors in KDEParameters.py?

### ISSUE THREAD

**Issue by KayShelton** [GeoscienceAustralia/tcrm#99]
In the _generatePDF function in the StatInterface/KDEParameters script, bandwidth (bw) is passed to the function, but not actually used in the kde.fit call. Is this intentional?

It results in bandwidth being re-calculated in the kde.fit, and sometimes coming back as zero, when it has been calculated as non-zero previously.

Passing bw=bw to the kde.fit call resolves the issue, but I wanted to make sure there wasn't a reason it had been left off.

**Comment by wcarthur** [comment]
Noted @KayShelton. In part, the `bw` kwarg possibly should be ignored in preference to calculating in `kde.fit`, where the calculation is dependent on the choice of kernel. The `bw` argument value is based on the `normal_reference` option in `kde.fit`, which is suitable for gaussian kernels, but not other options.
